### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by HamedFathi** [jeroenpot/SimpleInjector-AssemblyScanner#1]
Can you provide .NET Core release ?

**Comment by jeroenpot** [comment]
It is something i want to do. 
I'll see if i can make some time for this soon.

**Comment by jeroenpot** [comment]
I haven't gotting the solution compiling on appveyor yet, and i need to figure out how to make a nuget package that supports both net45 and core,
but there is source that compiles if you need it:
https://github.com/jeroenpot/SimpleInjector-AssemblyScanner/tree/feature/NetCore_Support/Source

**Comment by HamedFathi** [comment]
@jeroenpot  thank you so much

**Comment by jeroenpot** [comment]
I changed the project to work with .NET Standards 1.0 
So it supports .NET Core 1.0 And .NET 4.5.
Full matrix:
https://github.com/dotnet/standard/blob/master/docs/versions.md
